import { useState } from "react";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCog,
  faCaretRight,
  faFileAlt,
  faAngleDoubleLeft,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleRight,
  faTimesCircle,
  faCheckCircle,
  faQuestionCircle,
  faEdit,
  faEye,
  faCogs,
  faCubes,
  faCheck,
  faEyeSlash,
  faFilter,
  faTimes,
  faTrash,
  faExchangeAlt,
  faBorderAll,
  faChevronUp,
  faChevronDown,
  faClone,
  faLaptop,
  faTable,
  faGlobe,
  faWindowRestore,
  faPenFancy,
  faPlus,
  faTrashAlt,
  faLock,
  faOutdent,
  faSearch,
  faVials,
  faFileInvoiceDollar,
  faHome,
  faMoneyCheck,
  faVial,
  faSync,
  faChevronRight,
  faChevronLeft,
  faCircleInfo,
} from "@fortawesome/free-solid-svg-icons";
import { Dashboard } from "./Pages";
import { fab, faSearchengin } from "@fortawesome/free-brands-svg-icons";
library.add(
  fab,
  faCog,
  faSync,
  faChevronRight,
  faChevronLeft,
  faCaretRight,
  faFileAlt,
  faAngleDoubleLeft,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleRight,
  faTimesCircle,
  faCheckCircle,
  faQuestionCircle,
  faEdit,
  faEye,
  faCogs,
  faCubes,
  faCheck,
  faEyeSlash,
  faFilter,
  faTimes,
  faTrash,
  faExchangeAlt,
  faBorderAll,
  faChevronUp,
  faChevronDown,
  faClone,
  faLaptop,
  faTable,
  faGlobe,
  faWindowRestore,
  faPenFancy,
  faPlus,
  faTrashAlt,
  faLock,
  faOutdent,
  faSearch,
  faVials,
  faFileInvoiceDollar,
  faHome,
  faMoneyCheck,
  faVial,
  faSearchengin,
  faCircleInfo,
);

const App = () => {
  const [user] = useState(true);

  return user ? <Dashboard /> : null;
};

export default App;
